cloudinary/wdio-allure-ts

.travis.yml
lib/src/commons/BrowserUtils.d.ts
lib/src/commons/BrowserUtils.js
lib/src/commons/SpecialKeys.d.ts
lib/src/commons/SpecialKeys.js
package-lock.json
package.json
src/commons/BrowserUtils.ts
src/commons/SpecialKeys.ts
test/sampleApp/index.html
test/specs/TabsSpec.ts
test/wdio.conf.js

add switchTab, gettabIds and tests

Add switch tab

---

lib/src/commons/BrowserUtils.d.ts
lib/src/commons/BrowserUtils.js
src/commons/BrowserUtils.ts
src/enums/MouseButton.ts

Added following: 
mouseButtonDown(mouseButton?: string)
moveMouseCursorTo(selector ?: string, xOffset ?: number, yOffset ?: number) 
mouseButtonUp(mouseButton?: string)
function getElementLocation(selector : string) : {x:number; y:number} 
For Box POC (such as cropping etc')

Added boxing methods and element location method

---

lib/commons/BrowserUtils.d.ts
lib/commons/BrowserUtils.js
package-lock.json
package.json
src/commons/BrowserUtils.ts

add method to visually compare elements using wdio-image-comparison-service

add checkElement method using wdio-image-comparison-service

---

lib/commons/Reporter.d.ts
lib/commons/Reporter.js
package-lock.json
package.json
src/commons/Reporter.ts

Adding network logs audits and log it to report

Add browser network audits

---

package-lock.json
package.json

Reverts cloudinary/wdio-allure-ts#140

Revert "Single dependency"

---

package-lock.json
package.json
src/test/specs/SendKeysSpec.ts
src/test/wdio.conf.js

uses husky + lint-staged
triggers prettier on changes only
commit become a bit slower

Prettier on commit

---

src/test/sampleApp/index.html
src/test/specs/RefreshBrowserSpec.ts

I added New ts file RefreshBrowserSpec.ts 
Changes in sample app index.html.

Added RefreshBrowserSpec

---

src/test/sampleApp/index.html
src/test/specs/WaitForDisplayedSpec.ts

waitForDisplayedSpec

---

package-lock.json
src/commons/BrowserUtils.ts
src/commons/TestUtils.ts
src/test/sampleApp/index.html
src/test/specs/DragAndDropSpec.ts
src/test/specs/TestUtilsSpec.ts

https://cloudinary.atlassian.net/browse/APPS-6163

added drag and drop functionality

---

.eslintrc.js
package.json
yarn.lock

adding wdio plugin to eslint configuration

add-wdio-eslint-plugin

---

package.json
src/commons/BrowserUtils.ts
yarn.lock

remove deprecated remove-request-promise-native and use axios instead

remove-request-promise-native-dependency

---

src/commons/GitUtils.ts
src/commons/TestRailUtil.ts

Part of
[APPS-7501](https://cloudinary.atlassian.net/browse/APPS-7501)

Add get last merged files and tests ids by hours to git utils

---

src/commons/BrowserUtils.ts
src/test/specs/AddValueSpec.ts

Validate input enabled on value change

validate-enabled-on-value-change

---

src/commons/Reporter.ts

[APPS-9486](https://cloudinary.atlassian.net/browse/APPS-9486)

feat: add functionality for adding label to test

---

src/commons/BrowserUtils.ts
src/test/sampleApp/index.html
src/test/specs/GetValueSpec.ts

[APPS-9669](https://cloudinary.atlassian.net/browse/APPS-9669)

feat: add wdio getValue functionality

---

src/test/wdio.conf.js

increase max chrome instances for faster test execution

test: increase max chrome instances to 10

---

src/commons/Reporter.ts

make report logs cleaner:
- Keep network logs with status >= 400 only
- Keep browser logs with status SEVERE only

feat: cleaner-report-logs

---

CHANGELOG.md
README.md
package.json

Fix readme badges

---

package.json
src/commons/BrowserUtils.ts

remove chill out after switching to an iframe. no need anymore, and will save some time

Switch to frame no chillout

---

src/commons/GitUtils.ts
src/commons/TestFilesUtils.ts
src/commons/TestRailApi.ts
src/commons/TestRailUtil.ts

[APPS-10888](https://cloudinary.atlassian.net/browse/APPS-10888)

feat: add more logs to testRail script

---

.github/workflows/ci-pr-merge.yml
.github/workflows/publish-package.yml

newer wdio version does not work with node 12 anymore

test: bump node version in GitHub actions

---

src/test/specs/SwitchToParentFrameSpec.ts

Add new test for switch to parent frame

test: add new test for switch to parent frame

---

README.md

BREAKING CHANGE: move from sync to async mode
-
-
-

feat: sync to async

---

src/commons/GitUtils.ts
src/commons/TestFilesUtils.ts
src/scripts/updateTestRailTestsFromLastMerge.js
src/test/wdio.conf.js

https://cloudinary.atlassian.net/browse/QAUT-1730

feat: add get merged tests Ids since last merge functionality

---

src/commons/BrowserUtils.ts
src/test/sampleApp/index.html
src/test/specs/IsSelectedSpec.ts

feat: add isSelected function

---

src/commons/AllureReport.ts

- use text/html to properly display HTML in allure report
-
-

fix: use correct type for html attachment

---

package.json
src/test/wdio.conf.js
yarn.lock

feat: wdio_dependencies_update

---

src/test/wdio.conf.js

chore: change log level to error

---

CONTRIBUTING.md

-
Adding basic CONTRIBUTING.md
-
-

fix: CONTRIBUTING.md

---

src/commons/BrowserUtils.ts
src/test/specs/isDisplayedInViewportSpec.ts

feat: adding is displayed in viewport function

---

.github/workflows/ci-pr-merge.yml

fix: skip-slack-notification

---

src/commons/BrowserUtils.ts

test: Refactor waitForUrl function - change the condition to include

---

.github/workflows/publish-package.yml

fix: fix release flow

---

package.json
pnpm-lock.yaml

Add tsc to pretest

---

.github/workflows/publish-package.yml

fix: register npmjs

---

package.json

fix: remove login pm
